// Parity test: the JS hashes must be (almost) the same as the Python hashes of the same image.
// Fixtures are generated by `python -m decoder.tests.make_hash_fixtures`.
import { readFileSync } from 'node:fs'
import { PNG } from 'pngjs'
import { describe, expect, it } from 'vitest'
import { dhashFromGray32, gray32, hamming, hashFrame, phashFromGray32 } from '../src/hash'

const dir = new URL('./fixtures/', import.meta.url)
const fixtures: { file: string; phash: string; dhash: string; gray32: number[] }[] = JSON.parse(
  readFileSync(new URL('hashes.json', dir), 'utf8'),
)

describe('hash parity with Python', () => {
  for (const f of fixtures) {
    it(f.file, () => {
      const png = PNG.sync.read(readFileSync(new URL(f.file, dir)))
      const g = gray32(png.data, png.width, png.height)
      // Same 32x32 grayscale first (if this fails, the resize differs, not the DCT)
      const maxDiff = Math.max(...Array.from(g, (v, i) => Math.abs(v - f.gray32[i])))
      expect(maxDiff).toBeLessThan(0.5)

      const { phash, dhash } = hashFrame(png.data, png.width, png.height)
      expect(phash).toHaveLength(16)
      expect(hamming(phash, f.phash)).toBeLessThanOrEqual(4)
      expect(hamming(dhash, f.dhash)).toBeLessThanOrEqual(4)
      // Hashing Python's own 32x32 array isolates the DCT/dHash step
      expect(phashFromGray32(Float64Array.from(f.gray32))).toBe(f.phash)
      expect(dhashFromGray32(Float64Array.from(f.gray32))).toBe(f.dhash)
    })
  }
})

describe('hamming', () => {
  it('counts different bits', () => {
    expect(hamming('0000000000000000', '0000000000000000')).toBe(0)
    expect(hamming('0000000000000000', 'ffffffffffffffff')).toBe(64)
    expect(hamming('000000000000000f', '0000000000000001')).toBe(3)
  })
})
